title: Fluent Assertions
repository: fluentassertions/fluentassertions
description: "\"With Fluent Assertions, the assertions look beautiful, natural and most importantly, extremely readable.\""
email:
twitter_username: ddoomen
github_username:  fluentassertions
google_analytics: UA-99995670-1

header_pages:
  - examples.md
  - documentation.md
  - tips.md
  - releases.md
  - about.md

theme: minima
gems:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
